### ISSUE TITLE
TinyURL returning http instead of https

### ISSUE THREAD

**Issue by jsnmrs** [double-great/remark-lint-link-text#44]
While updating dependencies, I noticed six test failures, related to TinyURL returning `http://tinyurl.com...` instead of `https://tinyurl.com...`. It also looks like [our TinyURL dependency](https://github.com/JeffResc/TinyURL-Node.js) is no longer maintained (archived).

We should find an alternative.

![Screen Shot 2022-07-01 at 2 11 47 PM](https://user-images.githubusercontent.com/1215760/176948469-c272b1a2-05da-4763-a8aa-4a87e0462d46.jpg)

**Comment by katydecorah** [comment]
The http/https issue is resolved, but we should still find an alternative as it is listed as deprecated

**Comment by katydecorah** [comment]
Closing in favor of https://github.com/double-great/alt-text/issues/278

**Comment by katydecorah** [comment]
Whoops, reopening. These issues are not duplicates!
